### ISSUE TITLE
Fire and Soul Fire aren't in the inventory

### ISSUE THREAD

**Issue by AllyJaxx** [Totobird-Creations/AllTheUnobtainables-Mod#1]
Checked the inventory and the code and there don't seem to be any mentions of fire from what I have found, even though the mod claims to allow you to use fire.
![image](https://user-images.githubusercontent.com/64360185/183234816-49d9d8dd-4003-4679-bc71-0ffbea957383.png)
![image](https://user-images.githubusercontent.com/64360185/183234826-0b6c159c-2aa3-40ab-8711-d5fa251254bd.png)

**Comment by Totobird-Creations** [comment]
Thank you for bringing this to my attention. I just released a fix which you can find [here](https://modrinth.com/mod/alltheunobtainables/version/1.1.2).
Also, please note that you will not find these items in the `/give` command as they are not "real" items. They are actually wool and when the mod is installed server side, these items with special nbt data will be replaced by the expected block when placed.
